merged with master

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -70,3 +70,16 @@ jobs:
               echo "make job failed"
               exit $status
           fi
+
+    - name: Run AB
+      run: |
+          cd examples/ab
+          make node &
+          sleep 1
+          
+          timeout 6s make job || echo "make job terminated after timeout"
+          status=$?
+          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
+              echo "make job failed"
+              exit $status
+          fi
